CREATE TABLE `t_gamble_runtime` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键自增长',
  `donationCfg` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '捐锅',
  `gameid` int DEFAULT NULL COMMENT 'gameid',
  `startHoleindex` int NOT NULL COMMENT '起点',
  `ifShow` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'y' COMMENT '是否显示',
  `endHoleindex` int NOT NULL COMMENT '终点',
  `abstract` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '赌球摘要',
  `holePlayList` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '实际打球顺序',
  `groupid` int NOT NULL DEFAULT '1' COMMENT 'group',
  `creator_id` int NOT NULL COMMENT '创建人',
  `userRuleId` int NOT NULL DEFAULT '1' COMMENT 'UserRuleID',
  `gambleSysName` char(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '规则TAG',
  `gambleUserName` char(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '用户起名',
  `playersNumber` int NOT NULL DEFAULT '4' COMMENT '参数人数',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `red_blue_config` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '分组配置',
  `stroking_config` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '让杆配置JSON，格式：{"userid":{"对手userid":{"PAR3":1,"PAR4":0.5,"PAR5":0.5}}}',
  `val8421_config` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '8421用户加分配置JSON，格式：{"userid":{"Par+2":1,"Par+1":2,"Par":4,"Birdie":8}}',
  `bootstrap_order` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '出发顺序JSON，格式：[185,93,160,67]',
  `attenders` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '参与者JSON，格式：[185,93,160,67]',
  `ranking_tie_resolve_config` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'score.win_loss.reverse_score' COMMENT '排名冲突解决配置',
  `kickConfig` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '踢一脚',
  `bigWind` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'n' COMMENT '大风吹',
  PRIMARY KEY (`id`),
  KEY `fk_gamble_runtime_user_rule` (`userRuleId`),
  CONSTRAINT `fk_gamble_runtime_user_rule` FOREIGN KEY (`userRuleId`) REFERENCES `t_gamble_rule_user` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1344685 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='赌博配置表';