CREATE TABLE `t_course` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `country` varchar(100) DEFAULT 'China' COMMENT '国家',
  `pid` int NOT NULL COMMENT '省ID',
  `totalCount` int DEFAULT NULL,
  `courseid` int DEFAULT '0' COMMENT '球场ID',
  `name` varchar(255) DEFAULT NULL COMMENT '球场名',
  `designer` varchar(30) DEFAULT NULL COMMENT '设计者',
  `holeNumber` int DEFAULT '0' COMMENT '球洞编号',
  `totalPar` int DEFAULT '0',
  `totalYard` int DEFAULT '0',
  `icon150PictureID` int DEFAULT '0',
  `phoneNumber` int DEFAULT '0' COMMENT '电话号码',
  `dspprc` varchar(100) NOT NULL,
  `dspPrcMemo` varchar(255) DEFAULT NULL COMMENT '消费信息',
  `overallRating` int DEFAULT '0',
  `opStatus` varchar(50) DEFAULT NULL,
  `avatar` varchar(255) DEFAULT NULL COMMENT '球场照片缩略图',
  `lat` char(30) DEFAULT NULL,
  `lng` char(30) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
  `sLat` varchar(400) DEFAULT NULL,
  `sLgt` varchar(400) DEFAULT NULL,
  `tnum` int DEFAULT '0' COMMENT 'T台数量',
  `courtnum` int NOT NULL COMMENT '半场数量',
  `status` int DEFAULT '0' COMMENT '1为停用',
  PRIMARY KEY (`id`),
  KEY `courseID` (`courseid`, `name`),
  KEY `idx_lat` (`lat`),
  KEY `idx_lgt` (`lng`),
  KEY `idx_pid` (`pid`),
  KEY `idx_courseid` (`courseid`),
  FULLTEXT KEY `ind_cname` (`name`)
) ENGINE = InnoDB AUTO_INCREMENT = 37527 DEFAULT CHARSET = utf8mb3 COMMENT = '球场';

CREATE TABLE `t_course_court` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `courseid` int DEFAULT '0' COMMENT '球场ID',
  `courtid` int DEFAULT '0' COMMENT '半场ID',
  `courtname` varchar(400) DEFAULT NULL COMMENT '半场名称',
  `bak_field` varchar(400) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE KEY `courtid` (`courtid`)
) ENGINE = InnoDB AUTO_INCREMENT = 67350 DEFAULT CHARSET = utf8mb3 COMMENT = '球场对应半场';

CREATE TABLE `t_court_hole` (
  `holeid` int NOT NULL AUTO_INCREMENT,
  `courseid` int DEFAULT '0' COMMENT '球场ID',
  `coursename` varchar(400) DEFAULT NULL COMMENT '球场名称',
  `courtid` int DEFAULT '0' COMMENT '半场ID',
  `court_name` varchar(400) DEFAULT NULL,
  `hole_num` int DEFAULT '0',
  `fairwayid` int DEFAULT '0' COMMENT '球道ID',
  `holeno` int DEFAULT '0',
  `holename` varchar(10) DEFAULT NULL COMMENT '球洞标识',
  `par` int DEFAULT '0' COMMENT '标准杆',
  `black` int DEFAULT '0' COMMENT '黑T台',
  `gold` int DEFAULT '0' COMMENT '黄T台',
  `blue` int DEFAULT '0' COMMENT '蓝T台',
  `white` int DEFAULT '0' COMMENT '白T台',
  `red` int DEFAULT '0' COMMENT '红T台',
  `Tnum` int DEFAULT '0' COMMENT 'T台数目',
  `diffindex` int DEFAULT '0',
  `picid` int DEFAULT '0',
  `tips` varchar(4000) DEFAULT NULL,
  PRIMARY KEY (`holeid`),
  KEY `idx_courseid` (`courseid`),
  KEY `idx_holeid` (`holeid`),
  KEY `idx_courtid` (`courtid`)
) ENGINE = InnoDB AUTO_INCREMENT = 606130 DEFAULT CHARSET = utf8mb3 COMMENT = '半场对应球洞';

CREATE TABLE `t_friend` (
  `id` int NOT NULL AUTO_INCREMENT,
  `userid` int DEFAULT '0' COMMENT '用户id',
  `fuserid` int DEFAULT '0' COMMENT '对方id',
  `remark` varchar(400) DEFAULT NULL COMMENT '备注',
  `nickname` varchar(200) DEFAULT NULL COMMENT '备注昵称',
  `type` int DEFAULT '0',
  `status` int DEFAULT '1' COMMENT '状态',
  `clientid` int DEFAULT '0' COMMENT '客户端类型',
  `addtime` int DEFAULT '0' COMMENT '添加时间',
  `addip` varchar(20) DEFAULT NULL COMMENT '添加Ip',
  `lasttime` int DEFAULT '0' COMMENT '查看时间/接受时间',
  `lastip` varchar(20) DEFAULT NULL COMMENT '查看时间/接受ip',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_unq_userid_fuserid` (`userid`, `fuserid`),
  UNIQUE KEY `userid` (`userid`, `fuserid`),
  KEY `idx_userid` (`userid`),
  KEY `idx_fuserid` (`fuserid`),
  KEY `idx_status` (`status`)
) ENGINE = InnoDB AUTO_INCREMENT = 24026506 DEFAULT CHARSET = utf8mb3;

CREATE TABLE `t_gamble_algorithm` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `cfg_item` char(255) DEFAULT NULL,
  `cfg_memo` text,
  `cfg_value` char(255) DEFAULT NULL,
  `cfg_opt` char(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 8 DEFAULT CHARSET = utf8mb3;

CREATE TABLE `t_gamble_data_adjust` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `gambleid` int DEFAULT NULL,
  `pid` int DEFAULT NULL,
  `holeid` int DEFAULT NULL,
  `court_key` int DEFAULT NULL,
  `holename` char(20) DEFAULT NULL,
  `uid` int DEFAULT NULL,
  `title` char(10) DEFAULT NULL,
  `valid` tinyint(1) DEFAULT NULL,
  `money_hole` double DEFAULT NULL,
  `money_meat` double DEFAULT NULL,
  `money_guo` double DEFAULT NULL,
  `money` double DEFAULT NULL,
  `score_order` char(10) DEFAULT NULL,
  `debug` char(10) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_gambleid` (`gambleid`)
) ENGINE = InnoDB AUTO_INCREMENT = 783317 DEFAULT CHARSET = utf8mb3;

CREATE TABLE `t_gamble_game_alpha` (
  `gambleid` int unsigned NOT NULL AUTO_INCREMENT,
  `gameid` int DEFAULT NULL,
  `groupid` int DEFAULT NULL,
  `ename` char(40) DEFAULT NULL COMMENT '100',
  `gamblecfg` varchar(5000) DEFAULT NULL,
  `gamblecreator` int DEFAULT NULL,
  `ruleid` int DEFAULT NULL,
  `rulesource` char(10) DEFAULT NULL,
  `div_option` char(100) DEFAULT NULL,
  `playernum` int DEFAULT NULL,
  `players` char(100) DEFAULT NULL,
  `initorder` char(100) DEFAULT NULL,
  `fixed_dizhu` int DEFAULT NULL,
  `follower` int DEFAULT NULL,
  `agroup` char(100) DEFAULT NULL,
  `bgroup` char(100) DEFAULT NULL,
  `weaker` int DEFAULT NULL,
  `weak_par3_num` float DEFAULT NULL,
  `weak_par4_num` float DEFAULT NULL,
  `weak_par5_num` float DEFAULT NULL,
  `total_weak_num` int DEFAULT NULL,
  `addtime` datetime DEFAULT NULL,
  `unit` int DEFAULT NULL,
  `firstholeindex` int DEFAULT NULL,
  `lastholeindex` int DEFAULT NULL,
  `juanguo_point` int DEFAULT NULL,
  `juanguo_type` char(20) DEFAULT NULL,
  `showif` int DEFAULT NULL,
  `memo` varchar(400) DEFAULT NULL,
  `batchid` char(20) DEFAULT NULL,
  `batchbaseunit` int DEFAULT NULL,
  `weight_cfg` char(40) DEFAULT NULL,
  `value_8421` varchar(1000) DEFAULT NULL,
  PRIMARY KEY (`gambleid`),
  KEY `idx_gameid` (`gameid`),
  KEY `idx_groupid` (`groupid`),
  KEY `batchid` (`batchid`)
) ENGINE = InnoDB AUTO_INCREMENT = 689147 DEFAULT CHARSET = utf8mb3;

CREATE TABLE `t_gamble_kpi_cfg` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `kpi_name` char(11) DEFAULT NULL,
  `point` int DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 3 DEFAULT CHARSET = utf8mb3;

CREATE TABLE `t_gamble_rule_alpha` (
  `sysruleid` int unsigned NOT NULL AUTO_INCREMENT,
  `rulename` char(100) DEFAULT NULL,
  `ename` char(40) DEFAULT NULL,
  `playernum` int DEFAULT '0',
  `kpi_cfg` char(100) DEFAULT NULL,
  `div_options` char(30) DEFAULT NULL,
  `current_div_option` char(30) DEFAULT NULL,
  `duty_numbers` char(100) DEFAULT NULL COMMENT '包洞的成绩',
  `current_duty_number` char(100) DEFAULT NULL COMMENT '当前的包洞成绩',
  `duty_hole_only` char(1) DEFAULT NULL COMMENT '只包本洞,还是连以前的肉一起包',
  `duty_items` char(100) DEFAULT NULL COMMENT '包洞的项.',
  `max_options` char(100) DEFAULT NULL,
  `current_max_option` char(11) DEFAULT NULL,
  `bonus_operators` char(10) DEFAULT NULL,
  `bonus_switch` char(20) DEFAULT NULL COMMENT '头N总M的奖励开关:总赢才奖(zong_win)|总平或以上(zong_equal_or_up)|与总无关(zong_ignore)',
  `bonus_single_or_double` char(6) DEFAULT NULL,
  `current_bonus_operator` char(10) DEFAULT NULL,
  `single_bonus_value` char(250) DEFAULT NULL,
  `double_bonus_value` char(250) DEFAULT NULL,
  `draw_option` char(100) DEFAULT NULL COMMENT 'A=头尾都顶算顶洞,B=(头尾都顶算顶洞|头顶尾不顶),C=(头尾都顶算顶洞|头顶尾不顶|尾顶头不顶)',
  `meat_eat_condition` char(100) DEFAULT NULL COMMENT '吃肉的条件:win_hole(本洞赢了才吃)|win_kpi(输了也可以吃,各点吃各点)',
  `meat_hole_num_option` char(100) DEFAULT NULL COMMENT '能吃几块肉',
  `meat_value_option` char(100) DEFAULT NULL COMMENT '肉的值怎么计算:without_bonus(本洞输赢,不含奖励)|with_bonus(本洞输赢,含奖励)|kpi_separate(头吃头,尾吃尾)',
  `weight_cfg` char(40) DEFAULT NULL COMMENT '权重',
  `rule_memo` varchar(1000) DEFAULT '' COMMENT '2000',
  `draw_8421` char(30) DEFAULT NULL COMMENT '8421打平后顺延的成绩',
  `duty_8421` char(30) DEFAULT NULL COMMENT '8421包分选项',
  PRIMARY KEY (`sysruleid`)
) ENGINE = InnoDB AUTO_INCREMENT = 28 DEFAULT CHARSET = utf8mb3;

CREATE TABLE `t_gamble_rule_user` (
  `userruleid` int unsigned NOT NULL AUTO_INCREMENT,
  `sysruleid` int DEFAULT NULL,
  `userid` int DEFAULT NULL,
  `rulename` char(100) DEFAULT NULL,
  `playernum` int DEFAULT '0',
  `gambletype` char(10) DEFAULT NULL,
  `ab_cfg` char(20) DEFAULT NULL,
  `kpi_cfg` char(100) DEFAULT NULL,
  `kpi_operator` char(10) DEFAULT NULL,
  `maxed_cfg` char(100) DEFAULT NULL,
  `draw_cfg` char(100) DEFAULT NULL,
  `draw_hole_option` char(20) DEFAULT NULL,
  `duty_cfg` char(100) DEFAULT NULL,
  `bird_operator` char(10) DEFAULT NULL,
  `bird_number` int DEFAULT NULL,
  `eagle_operator` char(10) DEFAULT NULL,
  `eagle_number` int DEFAULT NULL,
  `albatross_operator` char(10) DEFAULT NULL,
  `albatross_number` int DEFAULT NULL,
  `ruleshow` char(1) DEFAULT 'Y',
  `akoption` int DEFAULT '0',
  `skin` int DEFAULT NULL,
  PRIMARY KEY (`userruleid`),
  KEY `idx_userid` (`userid`)
) ENGINE = InnoDB AUTO_INCREMENT = 4902 DEFAULT CHARSET = utf8mb3;

CREATE TABLE `t_gamble_rule_user_alpha` (
  `userruleid` int unsigned NOT NULL AUTO_INCREMENT,
  `sysruleid` int DEFAULT NULL,
  `userid` int DEFAULT NULL,
  `rulename` char(100) DEFAULT NULL,
  `ename` char(40) DEFAULT NULL,
  `playernum` int DEFAULT '0',
  `kpi_cfg` char(100) DEFAULT NULL,
  `div_options` char(30) DEFAULT NULL,
  `current_div_option` char(30) DEFAULT NULL,
  `duty_numbers` char(250) DEFAULT NULL,
  `current_duty_number` char(100) DEFAULT NULL,
  `duty_hole_only` char(1) DEFAULT NULL COMMENT '只包本洞,还是连以前的肉一起包',
  `duty_items` char(100) DEFAULT NULL COMMENT '包洞的项.',
  `max_options` char(100) DEFAULT NULL,
  `current_max_option` char(11) DEFAULT NULL,
  `bonus_operators` char(10) DEFAULT NULL,
  `bonus_switch` char(20) DEFAULT NULL,
  `bonus_single_or_double` char(6) DEFAULT NULL,
  `current_bonus_operator` char(10) DEFAULT NULL,
  `single_bonus_value` char(250) DEFAULT NULL,
  `double_bonus_value` char(250) DEFAULT NULL,
  `draw_option` char(100) DEFAULT NULL COMMENT 'A=头尾都顶算顶洞,B=(头尾都顶算顶洞|头顶尾不顶),C=(头尾都顶算顶洞|头顶尾不顶|尾顶头不顶)',
  `meat_hole_num_option` char(100) DEFAULT NULL,
  `meat_eat_condition` char(100) DEFAULT NULL COMMENT '吃肉的条件,即:怎么吃肉',
  `meat_value_option` char(100) DEFAULT NULL,
  `weight_cfg` char(40) DEFAULT NULL,
  `rule_memo` varchar(1000) DEFAULT '' COMMENT '1000',
  `draw_8421` char(30) DEFAULT NULL,
  `duty_8421` char(30) DEFAULT NULL,
  `ruleshow` char(1) DEFAULT NULL,
  PRIMARY KEY (`userruleid`),
  KEY `idx_userid` (`userid`)
) ENGINE = InnoDB AUTO_INCREMENT = 87037 DEFAULT CHARSET = utf8mb3;

CREATE TABLE `t_game` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(400) DEFAULT NULL COMMENT '比赛名称',
  `courseid` int DEFAULT '0' COMMENT '球场id',
  `teamid` int DEFAULT '0' COMMENT '球队id',
  `private` char(1) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '是否公开 参数为：y/n',
  `privacy_password` varchar(100) NOT NULL DEFAULT '' COMMENT '隐私口令',
  `remark` varchar(4000) DEFAULT '' COMMENT '备注',
  `gamestate` int DEFAULT NULL COMMENT '比赛状态',
  `creatorid` int DEFAULT '0' COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `starttime` datetime DEFAULT NULL COMMENT '开始比赛时间',
  `endtime` datetime DEFAULT NULL COMMENT '结束比赛时间',
  `is_oneball` tinyint NOT NULL DEFAULT '0' COMMENT '是否 OneBall 赛',
  PRIMARY KEY (`id`),
  KEY `idx_addid` (`creatorid`),
  KEY `idx_gamestate_privacy` (`gamestate`, `private`),
  KEY `idx_starttime_gametype` (`starttime`),
  KEY `idx_name` (`name`(255)),
  KEY `idx_courseid` (`courseid`),
  KEY `idx_teamid` (`teamid`),
  KEY `idx_starttime` (`starttime`),
  KEY `idx_courseid_gamestate` (`courseid`, `gamestate`),
  KEY `idx_courseid_gamestate_createtime` (`courseid`, `gamestate`, `create_time`),
  KEY `idx_courseid_gamestate_gameid` (`courseid`, `gamestate`, `id`),
  FULLTEXT KEY `fulltext_name` (`name`)
) ENGINE = InnoDB AUTO_INCREMENT = 1337844 DEFAULT CHARSET = utf8mb3 COMMENT = '比赛表';

CREATE TABLE `t_game_group` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `game_id` int unsigned NOT NULL COMMENT '比赛 ID',
  `group_no` tinyint NOT NULL COMMENT '组号，从 1 开始',
  `start_time` datetime DEFAULT NULL COMMENT '实际开球时间',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态 1=有效 0=无效',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_game_groupno` (`game_id`, `group_no`),
  KEY `idx_gameid` (`game_id`),
  CONSTRAINT `fk_game_group_game` FOREIGN KEY (`game_id`) REFERENCES `t_game` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb3 COMMENT = '比赛分组';

CREATE TABLE `t_game_interaction` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `game_id` int unsigned NOT NULL,
  `user_id` int NOT NULL,
  `type` tinyint NOT NULL COMMENT '1=点赞 2=评论',
  `content` varchar(1000) DEFAULT NULL COMMENT '评论内容',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '1=正常 0=删除',
  PRIMARY KEY (`id`),
  KEY `idx_game` (`game_id`),
  KEY `idx_user` (`user_id`),
  CONSTRAINT `fk_interaction_game` FOREIGN KEY (`game_id`) REFERENCES `t_game` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_interaction_user` FOREIGN KEY (`user_id`) REFERENCES `t_user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb3 COMMENT = '比赛互动';

CREATE TABLE `t_game_players` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `game_id` int unsigned NOT NULL COMMENT '比赛 ID',
  `group_id` int unsigned DEFAULT NULL COMMENT '分组 ID',
  `user_id` int NOT NULL COMMENT '用户 ID',
  `join_type` tinyint NOT NULL DEFAULT '1' COMMENT '加入方式 1=扫码 2=手动 3=老牌组合',
  `is_creator` tinyint NOT NULL DEFAULT '0' COMMENT '是否创建者',
  `handicap` decimal(10, 1) DEFAULT NULL COMMENT '差点',
  `t_land` varchar(10) DEFAULT NULL COMMENT '使用 T 台',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态 1=有效 0=退出',
  `join_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '加入时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_game_user` (`game_id`, `user_id`),
  KEY `idx_group` (`group_id`),
  KEY `idx_user` (`user_id`),
  CONSTRAINT `fk_players_game` FOREIGN KEY (`game_id`) REFERENCES `t_game_group` (`game_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_players_group` FOREIGN KEY (`group_id`) REFERENCES `t_game_group` (`id`) ON DELETE
  SET
    NULL ON UPDATE CASCADE,
    CONSTRAINT `fk_players_user` FOREIGN KEY (`user_id`) REFERENCES `t_user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb3 COMMENT = '比赛参赛人员';

CREATE TABLE `t_game_score` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `game_id` int unsigned NOT NULL,
  `user_id` int NOT NULL,
  `group_id` int DEFAULT NULL,
  `hole_id` int NOT NULL,
  `score` tinyint NOT NULL COMMENT '杆数',
  `putts` tinyint DEFAULT NULL COMMENT '推杆数',
  `fairway_hit` tinyint DEFAULT NULL COMMENT '球道命中 1/0',
  `gir` tinyint DEFAULT NULL COMMENT '标准杆上果岭 1/0',
  `sand_save` tinyint DEFAULT NULL COMMENT '沙坑救球 1/0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `recorder_type` char(10) DEFAULT NULL COMMENT '记录者类型',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_game_user_hole` (`game_id`, `user_id`, `hole_id`),
  KEY `idx_game_user` (`game_id`, `user_id`),
  KEY `fk_score_user` (`user_id`),
  KEY `fk_score_hole` (`hole_id`),
  CONSTRAINT `fk_score_game` FOREIGN KEY (`game_id`) REFERENCES `t_game` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_score_hole` FOREIGN KEY (`hole_id`) REFERENCES `t_court_hole` (`holeid`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_score_user` FOREIGN KEY (`user_id`) REFERENCES `t_user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb3 COMMENT = '比赛每洞成绩';

CREATE TABLE `t_user` (
  `id` int NOT NULL AUTO_INCREMENT,
  `openid` char(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `unionid` char(30) DEFAULT NULL,
  `token` char(40) DEFAULT NULL,
  `mobile` varchar(40) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT '' COMMENT '手机号',
  `wx_nickname` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '微信昵称',
  `avatar` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT 'user' COMMENT '个人头像路径',
  `follownum` int DEFAULT '0' COMMENT '关注数',
  `fansnum` int DEFAULT '0' COMMENT '粉丝数',
  `friendnum` int DEFAULT '0' COMMENT '好友数',
  `user_type` char(20) DEFAULT '0' COMMENT '用户类型',
  `status` int DEFAULT '0' COMMENT '用户状态',
  `addip` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '添加ip',
  `addtime` datetime DEFAULT NULL COMMENT '添加时间',
  `handicap` double(10, 1) DEFAULT NULL COMMENT '差点',
  `reg_type` char(1) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT 'U' COMMENT 'weixin,remark,remarkwithmobile,transfer',
  `helper_id` int DEFAULT NULL COMMENT '添加人的ID',
  PRIMARY KEY (`id`),
  KEY `idx_telephone` (`mobile`),
  KEY `idx_type` (`user_type`),
  KEY `idx_status` (`status`),
  KEY `index_nickname` (`wx_nickname`(191))
) ENGINE = InnoDB AUTO_INCREMENT = 837542 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;